In [1]:
import json
import pandas as pd

Happiness report data for 2017 were taken from [Kaggle](https://www.kaggle.com/unsdsn/world-happiness).

In [25]:
happy_data = pd.read_csv('happy_2017.csv')
happy_data.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [26]:
happy_data.shape

(155, 12)

In [27]:
happy_data.dtypes

Country                           object
Happiness.Rank                     int64
Happiness.Score                  float64
Whisker.high                     float64
Whisker.low                      float64
Economy..GDP.per.Capita.         float64
Family                           float64
Health..Life.Expectancy.         float64
Freedom                          float64
Generosity                       float64
Trust..Government.Corruption.    float64
Dystopia.Residual                float64
dtype: object

Table containing ISO-3 country code was taken from [here](https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/blob/master/all/all.csv).

In [29]:
country_codes = pd.read_csv('country_codes.csv')
country_codes.head()

,name,alpha-2,alpha-3,country-code,iso_3166-2,region,sub-region,intermediate-region,region-code,sub-region-code,intermediate-region-code
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,Asia,Southern Asia,NaN,142.0,34.0,NaN
1,Ã…land Islands,AX,ALA,248,ISO 3166-2:AX,Europe,Northern Europe,NaN,150.0,154.0,NaN
2,Albania,AL,ALB,8,ISO 3166-2:AL,Europe,Southern Europe,NaN,150.0,39.0,NaN
3,Algeria,DZ,DZA,12,ISO 3166-2:DZ,Africa,Northern Africa,NaN,2.0,15.0,NaN
4,American Samoa,AS,ASM,16,ISO 3166-2:AS,Oceania,Polynesia,NaN,9.0,61.0,NaN

In [37]:
merged_data = pd.merge(happy_data, country_codes, how='outer', left_on=['Country'], right_on=['name'], indicator=True)
merged_data.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,...,alpha-3,country-code,iso_3166-2,region,sub-region,intermediate-region,region-code,sub-region-code,intermediate-region-code,_merge
0,Norway,1.0,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,...,NOR,578.0,ISO 3166-2:NO,Europe,Northern Europe,NaN,150.0,154.0,NaN,both
1,Denmark,2.0,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,...,DNK,208.0,ISO 3166-2:DK,Europe,Northern Europe,NaN,150.0,154.0,NaN,both
2,Iceland,3.0,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,...,ISL,352.0,ISO 3166-2:IS,Europe,Northern Europe,NaN,150.0,154.0,NaN,both
3,Switzerland,4.0,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,...,CHE,756.0,ISO 3166-2:CH,Europe,Western Europe,NaN,150.0,155.0,NaN,both
4,Finland,5.0,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,...,FIN,246.0,ISO 3166-2:FI,Europe,Northern Europe,NaN,150.0,154.0,NaN,both

In [43]:
merged_data[merged_data._merge == 'left_only'].Country.values

array(['United States', 'United Kingdom', 'Czech Republic',
       'Taiwan Province of China', 'Russia', 'South Korea', 'Moldova',
       'Bolivia', 'North Cyprus', 'Hong Kong S.A.R., China', 'Kosovo',
       'Venezuela', 'Macedonia', 'Vietnam', 'Palestinian Territories',
       'Iran', 'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Ivory Coast',
       'Syria', 'Tanzania'], dtype=object)

In [44]:
merged_data[merged_data._merge == 'right_only'].name.values

array(['Ã…land Islands', 'American Samoa', 'Andorra', 'Anguilla',
       'Antarctica', 'Antigua and Barbuda', 'Aruba', 'Bahamas',
       'Barbados', 'Bermuda', 'Bolivia (Plurinational State of)',
       'Bonaire, Sint Eustatius and Saba', 'Bouvet Island',
       'British Indian Ocean Territory', 'Brunei Darussalam',
       'Cabo Verde', 'Cayman Islands', 'Christmas Island',
       'Cocos (Keeling) Islands', 'Comoros', 'Congo',
       'Congo, Democratic Republic of the', 'Cook Islands',
       "CÃ´te d'Ivoire", 'Cuba', 'CuraÃ§ao', 'Czechia', 'Djibouti',
       'Dominica', 'Equatorial Guinea', 'Eritrea', 'Eswatini',
       'Falkland Islands (Malvinas)', 'Faroe Islands', 'Fiji',
       'French Guiana', 'French Polynesia', 'French Southern Territories',
       'Gambia', 'Gibraltar', 'Greenland', 'Grenada', 'Guadeloupe',
       'Guam', 'Guernsey', 'Guinea-Bissau', 'Guyana',
       'Heard Island and McDonald Islands', 'Holy See', 'Hong Kong',
       'Iran (Islamic Republic of)', 'Isle of Man', 'Jersey', 'Kiribati',
       "Korea (Democratic People's Republic of)", 'Korea, Republic of',
       "Lao People's Democratic Republic", 'Liechtenstein', 'Macao',
       'Maldives', 'Marshall Islands', 'Martinique', 'Mayotte',
       'Micronesia (Federated States of)', 'Moldova, Republic of',
       'Monaco', 'Montserrat', 'Nauru', 'New Caledonia', 'Niue',
       'Norfolk Island', 'North Macedonia', 'Northern Mariana Islands',
       'Oman', 'Palau', 'Palestine, State of', 'Papua New Guinea',
       'Pitcairn', 'Puerto Rico', 'RÃ©union', 'Russian Federation',
       'Saint BarthÃ©lemy', 'Saint Helena, Ascension and Tristan da Cunha',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Martin (French part)', 'Saint Pierre and Miquelon',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Seychelles', 'Sint Maarten (Dutch part)',
       'Solomon Islands', 'South Georgia and the South Sandwich Islands',
       'Suriname', 'Svalbard and Jan Mayen', 'Syrian Arab Republic',
       'Taiwan, Province of China', 'Tanzania, United Republic of',
       'Timor-Leste', 'Tokelau', 'Tonga', 'Turks and Caicos Islands',
       'Tuvalu', 'United Kingdom of Great Britain and Northern Ireland',
       'United States of America', 'United States Minor Outlying Islands',
       'Vanuatu', 'Venezuela (Bolivarian Republic of)', 'Viet Nam',
       'Virgin Islands (British)', 'Virgin Islands (U.S.)',
       'Wallis and Futuna', 'Western Sahara'], dtype=object)

In [49]:
rename_dict = {
    'United States': 'United States of America', 
    'United Kingdom': 'United Kingdom of Great Britain and Northern Ireland', 
    'Czech Republic': 'Czechia',
    'Taiwan Province of China': 'Taiwan, Province of China', 
    'Russia': 'Russian Federation', 
    'South Korea': 'Korea, Republic of', 
    'Moldova': 'Moldova, Republic of',
    'Bolivia': 'Bolivia (Plurinational State of)', 
    'Hong Kong S.A.R., China': 'Hong Kong', 
    'Venezuela': 'Venezuela (Bolivarian Republic of)', 
    'Macedonia': 'North Macedonia', 
    'Vietnam': 'Viet Nam', 
    'Palestinian Territories': 'Palestine, State of',
    'Iran': 'Iran (Islamic Republic of)', 
    'Congo (Brazzaville)': 'Congo', 
    'Congo (Kinshasa)': 'Congo, Democratic Republic of the', 
    'Ivory Coast': "CÃ´te d'Ivoire",
    'Syria': 'Syrian Arab Republic', 
    'Tanzania': 'Tanzania, United Republic of' 
}
happy_data = happy_data.replace(rename_dict)
happy_data.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

In [52]:
happy_data = happy_data[~happy_data['Country'].isin(['North Cyprus', 'Kosovo'])]

In [53]:
merged_data = pd.merge(happy_data, country_codes, how='left', left_on=['Country'], right_on=['name'], indicator=True)
merged_data.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,...,alpha-3,country-code,iso_3166-2,region,sub-region,intermediate-region,region-code,sub-region-code,intermediate-region-code,_merge
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,...,NOR,578,ISO 3166-2:NO,Europe,Northern Europe,NaN,150.0,154.0,NaN,both
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,...,DNK,208,ISO 3166-2:DK,Europe,Northern Europe,NaN,150.0,154.0,NaN,both
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,...,ISL,352,ISO 3166-2:IS,Europe,Northern Europe,NaN,150.0,154.0,NaN,both
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,...,CHE,756,ISO 3166-2:CH,Europe,Western Europe,NaN,150.0,155.0,NaN,both
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,...,FIN,246,ISO 3166-2:FI,Europe,Northern Europe,NaN,150.0,154.0,NaN,both

In [54]:
merged_data[merged_data._merge == 'left_only'].Country.values

array([], dtype=object)

In [55]:
merged_data.shape

(153, 24)

GeoJSON was taken from [here](https://github.com/datasets/geo-countries/blob/master/data/countries.geojson).

In [83]:
with open('countries.geojson', 'r') as f:
    geojson = json.load(f)
countries = {}
for i in range(len(geojson['features'])):
    countries[geojson['features'][i]['properties']['ISO_A3']] = geojson['features'][i]['properties']['ADMIN']
countries

{'ABW': 'Aruba',
 'AFG': 'Afghanistan',
 'AGO': 'Angola',
 'AIA': 'Anguilla',
 'ALB': 'Albania',
 'ALA': 'Aland',
 'AND': 'Andorra',
 'ARE': 'United Arab Emirates',
 'ARG': 'Argentina',
 'ARM': 'Armenia',
 'ASM': 'American Samoa',
 'ATA': 'Antarctica',
 '-99': 'Akrotiri Sovereign Base Area',
 'ATF': 'French Southern and Antarctic Lands',
 'ATG': 'Antigua and Barbuda',
 'AUS': 'Australia',
 'AUT': 'Austria',
 'AZE': 'Azerbaijan',
 'BDI': 'Burundi',
 'BEL': 'Belgium',
 'BEN': 'Benin',
 'BFA': 'Burkina Faso',
 'BGD': 'Bangladesh',
 'BGR': 'Bulgaria',
 'BHR': 'Bahrain',
 'BHS': 'The Bahamas',
 'BIH': 'Bosnia and Herzegovina',
 'BLM': 'Saint Barthelemy',
 'BLR': 'Belarus',
 'BLZ': 'Belize',
 'BMU': 'Bermuda',
 'BOL': 'Bolivia',
 'BRA': 'Brazil',
 'BRB': 'Barbados',
 'BRN': 'Brunei',
 'BTN': 'Bhutan',
 'BWA': 'Botswana',
 'CAF': 'Central African Republic',
 'CAN': 'Canada',
 'CHE': 'Switzerland',
 'CHL': 'Chile',
 'CHN': 'China',
 'CIV': 'Ivory Coast',
 'CMR': 'Cameroon',
 'COD': 'Democratic Republic of the Congo',
 'COG': 'Republic of Congo',
 'COK': 'Cook Islands',
 'COL': 'Colombia',
 'COM': 'Comoros',
 'CPV': 'Cape Verde',
 'CRI': 'Costa Rica',
 'CUB': 'Cuba',
 'CUW': 'CuraÃ§ao',
 'CYM': 'Cayman Islands',
 'CYP': 'Cyprus',
 'CZE': 'Czech Republic',
 'DEU': 'Germany',
 'DJI': 'Djibouti',
 'DMA': 'Dominica',
 'DNK': 'Denmark',
 'DOM': 'Dominican Republic',
 'DZA': 'Algeria',
 'ECU': 'Ecuador',
 'EGY': 'Egypt',
 'ERI': 'Eritrea',
 'ESP': 'Spain',
 'EST': 'Estonia',
 'ETH': 'Ethiopia',
 'FIN': 'Finland',
 'FJI': 'Fiji',
 'FLK': 'Falkland Islands',
 'FRA': 'France',
 'FRO': 'Faroe Islands',
 'FSM': 'Federated States of Micronesia',
 'GAB': 'Gabon',
 'GBR': 'United Kingdom',
 'GEO': 'Georgia',
 'GGY': 'Guernsey',
 'GHA': 'Ghana',
 'GIB': 'Gibraltar',
 'GIN': 'Guinea',
 'GMB': 'Gambia',
 'GNB': 'Guinea Bissau',
 'GNQ': 'Equatorial Guinea',
 'GRC': 'Greece',
 'GRD': 'Grenada',
 'GRL': 'Greenland',
 'GTM': 'Guatemala',
 'GUM': 'Guam',
 'GUY': 'Guyana',
 'HKG': 'Hong Kong S.A.R.',
 'HMD': 'Heard Island and McDonald Islands',
 'HND': 'Honduras',
 'HRV': 'Croatia',
 'HTI': 'Haiti',
 'HUN': 'Hungary',
 'IDN': 'Indonesia',
 'IMN': 'Isle of Man',
 'IND': 'India',
 'IOT': 'British Indian Ocean Territory',
 'IRL': 'Ireland',
 'IRN': 'Iran',
 'IRQ': 'Iraq',
 'ISL': 'Iceland',
 'ISR': 'Israel',
 'ITA': 'Italy',
 'JAM': 'Jamaica',
 'JEY': 'Jersey',
 'JOR': 'Jordan',
 'JPN': 'Japan',
 'KAZ': 'Kazakhstan',
 'KEN': 'Kenya',
 'KGZ': 'Kyrgyzstan',
 'KHM': 'Cambodia',
 'KIR': 'Kiribati',
 'KNA': 'Saint Kitts and Nevis',
 'KOR': 'South Korea',
 'KWT': 'Kuwait',
 'LAO': 'Laos',
 'LBN': 'Lebanon',
 'LBR': 'Liberia',
 'LBY': 'Libya',
 'LCA': 'Saint Lucia',
 'LIE': 'Liechtenstein',
 'LKA': 'Sri Lanka',
 'LSO': 'Lesotho',
 'LTU': 'Lithuania',
 'LUX': 'Luxembourg',
 'LVA': 'Latvia',
 'MAC': 'Macao S.A.R',
 'MAF': 'Saint Martin',
 'MAR': 'Morocco',
 'MCO': 'Monaco',
 'MDA': 'Moldova',
 'MDG': 'Madagascar',
 'MDV': 'Maldives',
 'MEX': 'Mexico',
 'MHL': 'Marshall Islands',
 'MKD': 'Macedonia',
 'MLI': 'Mali',
 'MLT': 'Malta',
 'MMR': 'Myanmar',
 'MNE': 'Montenegro',
 'MNG': 'Mongolia',
 'MNP': 'Northern Mariana Islands',
 'MOZ': 'Mozambique',
 'MRT': 'Mauritania',
 'MSR': 'Montserrat',
 'MUS': 'Mauritius',
 'MWI': 'Malawi',
 'MYS': 'Malaysia',
 'NAM': 'Namibia',
 'NCL': 'New Caledonia',
 'NER': 'Niger',
 'NFK': 'Norfolk Island',
 'NGA': 'Nigeria',
 'NIC': 'Nicaragua',
 'NIU': 'Niue',
 'NLD': 'Netherlands',
 'NOR': 'Norway',
 'NPL': 'Nepal',
 'NRU': 'Nauru',
 'NZL': 'New Zealand',
 'OMN': 'Oman',
 'PAK': 'Pakistan',
 'PAN': 'Panama',
 'PCN': 'Pitcairn Islands',
 'PER': 'Peru',
 'PHL': 'Philippines',
 'PLW': 'Palau',
 'PNG': 'Papua New Guinea',
 'POL': 'Poland',
 'PRI': 'Puerto Rico',
 'PRK': 'North Korea',
 'PRT': 'Portugal',
 'PRY': 'Paraguay',
 'PSE': 'Palestine',
 'PYF': 'French Polynesia',
 'QAT': 'Qatar',
 'ROU': 'Romania',
 'RUS': 'Russia',
 'RWA': 'Rwanda',
 'ESH': 'Western Sahara',
 'SAU': 'Saudi Arabia',
 'SDN': 'Sudan',
 'SSD': 'South Sudan',
 'SEN': 'Senegal',
 'SGP': 'Singapore',
 'SGS': 'South Georgia and South Sandwich Islands',
 'SHN': 'Saint Helena',
 'SLB': 'Solomon Islands',
 'SLE': 'Sierra Leone',
 'SLV': 'El Salvador',
 'SMR': 'San Marino',
 'SOM': 'Somalia',
 'SPM': 'Saint Pierre and Miquelon',
 'SRB': 'Republic of Serbia',
 'STP': 'Sao Tome and Principe',
 'SUR': 'Suriname',
 'SVK': 'Slovakia',
 'SVN': 'Slovenia',
 'SWE': 'Sweden',
 'SWZ': 'Swaziland',
 'SXM': 'Sint Maarten',
 'SYC': 'Seychelles',
 'SYR': 'Syria',
 'TCA': 'Turks and Caicos Islands',
 'TCD': 'Chad',
 'TGO': 'Togo',
 'THA': 'Thailand',
 'TJK': 'Tajikistan',
 'TKM': 'Turkmenistan',
 'TLS': 'East Timor',
 'TON': 'Tonga',
 'TTO': 'Trinidad and Tobago',
 'TUN': 'Tunisia',
 'TUR': 'Turkey',
 'TUV': 'Tuvalu',
 'TWN': 'Taiwan',
 'TZA': 'United Republic of Tanzania',
 'UGA': 'Uganda',
 'UKR': 'Ukraine',
 'UMI': 'United States Minor Outlying Islands',
 'URY': 'Uruguay',
 'USA': 'United States of America',
 'UZB': 'Uzbekistan',
 'VAT': 'Vatican',
 'VCT': 'Saint Vincent and the Grenadines',
 'VEN': 'Venezuela',
 'VGB': 'British Virgin Islands',
 'VIR': 'United States Virgin Islands',
 'VNM': 'Vietnam',
 'VUT': 'Vanuatu',
 'WLF': 'Wallis and Futuna',
 'WSM': 'Samoa',
 'YEM': 'Yemen',
 'ZAF': 'South Africa',
 'ZMB': 'Zambia',
 'ZWE': 'Zimbabwe'}

In [81]:
merged_data[~merged_data['alpha-3'].isin(countries.keys())]

Empty DataFrame
Columns: [Country, Happiness.Rank, Happiness.Score, Whisker.high, Whisker.low, Economy..GDP.per.Capita., Family, Health..Life.Expectancy., Freedom, Generosity, Trust..Government.Corruption., Dystopia.Residual, name, alpha-2, alpha-3, country-code, iso_3166-2, region, sub-region, intermediate-region, region-code, sub-region-code, intermediate-region-code, _merge]
Index: []

[0 rows x 24 columns]